spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/ecomweb
  mongodb:
    uri: mongodb://localhost:27017/ecommerce
    database: ecommerce
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: notification_service
    local-datacenter: datacenter1   # T�n DC trong cluster Cassandra
    schema-action: none
    request:
      timeout: 10s
    username: cassandra
    password: cassandra

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
server:
  port: 8082
  servlet:
    context-path: /notifications
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # mở endpoint prometheus
  endpoint:
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true